# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "cargo" # See documentation for possible values
    directory: "/backend" # Location of package manifests
    schedule:
      interval: "monthly"
    groups:
      cargo-minor-and-patch-deps:
        update-types:
          - "minor"
          - "patch"
      cargo-major-deps:
        update-types:
          - "major"
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/frontend" # Location of package manifests
    schedule:
      interval: "monthly"
    groups:
      npm-minor-and-patch-deps:
        update-types:
          - "minor"
          - "patch"
      npm-major-deps:
        update-types:
          - "major"
  - package-ecosystem: "github-actions" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "monthly"
    groups:
      github-actions-deps:
        patterns:
          - '*'
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "monthly"
