# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "cargo"
    directories:
      - "/backend"
      - "/healthz"
      - "/"
    schedule:
      interval: "quarterly"
    groups:
      cargo-deps:
        patterns:
          - "*"
  - package-ecosystem: "npm"
    directories:
      - "/frontend"
    schedule:
      interval: "quarterly"
    groups:
      npm-deps:
        patterns:
          - "*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "quarterly"
    groups:
      github-actions-deps:
        patterns:
          - "*"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "quarterly"
    groups:
      docker-deps:
        patterns:
          - "*"
