# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
multi-ecosystem-groups:
  all-deps:
    interval: monthly
updates:
  - package-ecosystem: "cargo"
    directories:
      - "/backend"
      - "/healthz"
      - "/"
    patterns:
      - "*"
    multi-ecosystem-group: "all-deps"
  - package-ecosystem: "npm"
    directories:
      - "/frontend"
    patterns:
      - "*"
    multi-ecosystem-group: "all-deps"
  - package-ecosystem: "github-actions"
    directory: "/"
    patterns:
      - "*"
    multi-ecosystem-group: "all-deps"
  - package-ecosystem: "docker"
    directory: "/"
    patterns:
      - "*"
    multi-ecosystem-group: "all-deps"
