[env]
# Default variables for developers running cargo run and cargo test.
DATABASE_URL = "postgresql://localhost/koso"
TESTONLY_ENABLE_DEV = "true"
GH_APP_ENV = "dev"
RUST_BACKTRACE = "1"
RUST_LOG = "koso=trace,tower_http=trace,sqlx=trace,axum=trace,info"
SECRETS_DIR = "../.secrets"
