name: "Find Docker Image Cache Name"
description: "Determines the cache name for Docker images based on PR or main branch."
outputs:
  result:
    description: "Cache name for Docker image"
    value: ${{ steps.get-docker-image-cache-name.outputs.result }}
runs:
  using: "composite"
  steps:
    - name: Find docker image cache
      id: get-docker-image-cache-name
      uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
      with:
        result-encoding: string
        script: |
          const script = require('.github/actions/find-docker-image-cache/script.js')
          const result = await script({github, context});
          console.log(`Found cache: ${result}`);
          return result;
